name: Build and Deploy Node.js App to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name             # ⬅️ Replace with your Azure Web App name
  NODE_VERSION: '20.x'
  BUILD_OUTPUT: 'dist'                         # ⬅️ Replace with your actual build folder (e.g., build, out, .next)

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ env.BUILD_OUTPUT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ${{ env.BUILD_OUTPUT }}

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.BUILD_OUTPUT }}
