name: Build and deploy Node.js app to Azure Web App - copilotapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_OUTPUT: dist  # Vite default build folder

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Fix vite permissions (optional, but recommended)
        run: chmod +x ./node_modules/.bin/vite

      - name: Build the app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ env.BUILD_OUTPUT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ${{ env.BUILD_OUTPUT }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'copilotapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_95BC738C90AE40B5B0B8EEBCC816ACD3 }}
          package: ${{ env.BUILD_OUTPUT }}
